### ISSUE TITLE
Rückgabewert "{"status":"error"}" beim initialen Konfigurieren von SkIDentity

### ISSUE THREAD

**Issue by UweKeim** [eid-login/eid-login-wordpress#1]
Habe ein Weblog auf Apache unter Windows und gerade Eurer Plug-in installiert und aktiviert.

Beim Klick auf <kbd>Weiter mit SkIDentity</kbd> passiert nichts, und in der Browser-Console sehe ich u. a.:

```
/wp-json/eidlogin/v1/eidlogin-settings 500 (Internal Server Error)
```

Der Response dieser Anfrage ist schlicht eine JSON-Datei mit folgendem Inhalt:

```json
{"status":"error"}
```

In den Protokolldateien von Apache habe ich nichts gefunden zu dem Issue.

### Frage: 

Gibt es eine Chance, das genauer zu untersuchen? (Irgendwelche Protokolldateien auf dem Server?) und final dann auch den Fehler zu beseitigen?

**Comment by ecmrauh** [comment]
Da beim Klick auf `Weiter mit SkIDentity` u.a. auch ein neues Schlüsselpaar erzeugt wird und hierfür das PHP-Modul `openssl` benötigt wird, könnte ich mir vorstellen, dass dieses eventuell fehlt bzw. noch aktiviert werden muss. Ob das Modul vorhanden ist, kann man prüfen z.B. mit:

`php -m | grep openssl`

Wenn die Ausgabe leer ist, fehlt das Modul.

**Comment by UweKeim** [comment]
Danke. Leider nicht, das hier sind die PHP-Module, die installiert sind:

```txt
[PHP Modules]
bcmath
calendar
com_dotnet
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
soap
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib
```

Vermutlich ist Windows als Zielsystem für das Plug-in nicht vorgesehen. 

Ich probiere ggf. zu einem späteren Zeitpunkt mal auf Linux. 

Danke für Deine schnelle Rückmeldung 😊👍🏻
