### ISSUE TITLE
Link zum Plugin auf wordpress.org

### ISSUE THREAD

**Issue by w-sky** [eid-login/eid-login-wordpress#2]
Hallo, auf https://www.personalausweisportal.de/SharedDocs/anwendungen/Webs/PA/DE/Unternehmen/WordPress_Plugin_ecsec.html gibt es nur einen Link hierhin, zu github.com, aber keinen Hinweis darauf, dass das Plugin auch auf wordpress.org verfügbar ist.
Das ist ziemlich verwirrend und zunächst enttäuschend, weil es ziemlich mühsam und umständlich wäre, das Plugin von github herunterzuladen und zu installieren.
Um es zu vereinfachen, sollte bei Informationen zum Plugin die Wordpress.org-Adresse publiziert werden, oder es sollte hier in der ersten sichtbaren Projektbeschreibung verlinkt werden, damit man nicht erst lange suchen und grübeln muss.

**Comment by ecmrauh** [comment]
Vielen Dank für den Hinweis! Der Satz zur Installation in diesem Repo wurde soeben ergänzt und die Anfrage bzgl. `personalausweisportal.de` an die Kollegen weitergeleitet.

**Comment by ecmrauh** [comment]
Der Text auf [personalausweisportal.de](https://www.personalausweisportal.de/SharedDocs/anwendungen/Webs/PA/DE/Unternehmen/WordPress_Plugin_ecsec.html) wurde entsprechend angepasst.
