### ISSUE TITLE
eID - nur für Admin?

### ISSUE THREAD

**Issue by charly1080** [eid-login/eid-login-wordpress#5]
Hallo eID-Team,

ich habe das Plugin "eID-Login" unter WordPress 6.5.4 installiert und für mich als Admin erfolgreich getestet.
Hier kann ich auch im Profil meines Benutzers unter eID-Login die Zeilen Status und Status ändern sehen, wo ich z.B. die "Verknüpfung zu eID erstellen" oder löschen kann

bei weiteren Benutzen sehe ich den Abschnitt "eID-Login" im Profil des jeweiligen Benutzers nicht.
Was mache ich falsch? oder funktioniert der eID-Login nur für den Admin?

Vielen Dank im Voraus für Ihre Hilfe

Viele Grüße Daniel

**Comment by ecmrauh** [comment]
Hallo Daniel,

das Plugin sollte für alle Benutzer funktionieren, nicht nur für den Admin. Ich habe es gerade getestet und alles hat funktioniert wie erwartet. Möglicherweise hängt es mit dem Issue #6  zusammen (siehe dort).

Gruß
Michael
