### ISSUE TITLE
eID in WordPress mit WooCommerce - eID-Login nicht angezeigt

### ISSUE THREAD

**Issue by charly1080** [eid-login/eid-login-wordpress#6]
Hallo eID-Login-Team,

unter WordPress 6.5.4 nutze ich das Plugin WooCommerce für den Shop wird der Login url/mein-konto/ genutzt auf dieser Seite wird der Login über eID nicht angeboten.
auf der Seite url/wp-login.php?loggedout=true&wp_lang=de_DE wird der eID-Login angeboten.
Was mach ich falsch?
Was kann ich tun, dass auch auf der mein-konto Seite der eID-Login angeboten wird

vielen Dank im Voraus für Ihre Hilfe

Viele Grüße Daniel

**Comment by ecmrauh** [comment]
Hallo Daniel,

unser Plugin wurde nicht zusammen mit dem Plugin WooCommerce getestet. Allerdings wurden uns bisher auch keine Probleme berichtet. Ich kann versuchen, das Problem in unserer Testinstanz nachzustellen (das kann allerdings ein bisschen dauern).

Gruß
Michael
