### ISSUE TITLE
neuer Benutzer mit eID anlegen

### ISSUE THREAD

**Issue by charly1080** [eid-login/eid-login-wordpress#7]
Hallo eID-Team,

ist es möglich, wenn ein neuer Benutzer auf meine Seite kommt, dass dieser sich nur mit eID-Login mit Hilfe des Personalausweises anmeldet und somit alle erforderlichen Daten (nach Möglichkeit wählbar durch Admin):
- Vorname
- Nachname
- Adresse
- PLZ
- Ort
angelegt werden und der neue Benutzer somit verfügbar ist und im Shop aggieren kann?

Vielen Dank im Voraus für Ihre Hilfe

Viele Grüße Daniel

**Comment by ecmrauh** [comment]
Hallo Daniel,

grundsätzlich ist es so, dass sich Benutzer erst regulär registrieren und dann in ihrem Profil den Personalausweis „verbinden“. Hierfür braucht es keine weiteren Attribute wie z.B. Vor- und Nachnamen, es reicht das sogenannte Pseudonym (eIdentifier). Trotzdem können weitere Attribute angefordert und übertragen werden.

Das Auslesen der Daten aus dem Personalausweis erfolgt über den Dienst „SkIDentity“. Sofern nur das Pseudonym ausgelesen wird, ist dieser Service kostenlos (siehe auch Frage A8 unter https://eid.services/help.html). Das Auslesen weiterer Attribute kostet dann jedoch 399 Euro pro Monat (siehe https://www.skidentity.de/service-provider/skidentity-dienst/#pricing).

Selbst wenn die Attribute von SkIDentity mitgeliefert werden, ist eine Auswahl durch den Admin aber derzeit nicht möglich.

Gruß
Michael
